### ISSUE TITLE
Hey, what is the game_info.json file?

### ISSUE THREAD

**Issue by NaikKhushi21** [daveaditya/CSCI_561_AI#2]

**Comment by daveaditya** [comment]
Hello. The `game_info.json` stores the last step in the minimax tree that the agent used as the move. The schema of the file is as follows:

```JSON
{"step": 0}
```

**Comment by NaikKhushi21** [comment]
I tried to run your code but there is one key error stating:
KeyError                                  Traceback (most recent call last)
[<ipython-input-16-71e2df30251d>](https://localhost:8080/#) in <cell line: 550>()
    558     )
    559     piece_type, previous_board, current_board = go.piece, go.previous_board, go.current_board
--> 560     step = load_game_info(previous_board, current_board)
    561 
    562     my_player = MyPlayer(

[<ipython-input-11-2f21a5de56eb>](https://localhost:8080/#) in load_game_info(previous_board, current_board)
     28         with open(GAME_INFO_FILE_PATH, mode="r") as game_info_file:
     29             game_info = json.load(game_info_file)
---> 30             step = game_info["step"] + 2
     31 
     32     # Store updated game info

KeyError: 'step'

**Comment by daveaditya** [comment]
Looks like your json file is missing the `step` key. Try using the default schema I shared above in your json file. Also make sure that the JSON file path and file name are correct. The paths are set in the `constants.py` file.

**Comment by NaikKhushi21** [comment]
Hey, the issue got resolved. Sorry for bothering you. Thanks again!

**Comment by daveaditya** [comment]
Glad it worked.
